### ISSUE TITLE
Update code of Conduct

### ISSUE THREAD

**Issue by srepollock** [srepollock/divine-engine#38]
https://www.contributor-covenant.org/version/1/4/code-of-conduct.md

**Comment by Michael-Overall** [comment]
I can add that to the repo if you like.

Should this code of conduct file be linked from CONTRIBUTING.md?

Also, I think the link to CONTRIBUTING.md from README.md may be broken ( see #39 )

**Comment by srepollock** [comment]
Hey @Michael-Overall that would be fantastic if you could add a code of conduct to the project. I have a few minor things to fix up in the contributing file but this would help take a task off my hands thank you!
Would you mind making this a pull request for this as well? Thanks in advance!
